---
# tasks file for sap-hana-preconfigure configuration

- debug:
    msg: "sapnote/assert-2292690.yml"

- import_tasks: 2292690/01-assert-tuned.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_01|d(false)

- import_tasks: 2292690/02-assert-auto-numa-balancing.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_02|d(false)

- import_tasks: 2292690/03-assert-thp.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_03|d(false)

- import_tasks: 2292690/04-assert-c-states-for-lower-latency.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_04|d(false)

- import_tasks: 2292690/05-assert-cpu-governor.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_05|d(false)

- import_tasks: 2292690/06-assert-epb.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_06|d(false)

- import_tasks: 2292690/07-assert-ksm.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_07|d(false)

# SELinux is already configured in role sap-preconfigure:
#- import_tasks: 2292690/08-assert-selinux.yml
#  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_08|d(false)

- import_tasks: 2292690/09-assert-etc-sudoers.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_09|d(false)

- import_tasks: 2292690/10-assert-ibm-energyscale.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_10|d(false)

...
