---

- debug:
    msg: "imported RedHat/generic/assert-thp.yml"

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never"
- block:
    - name: Get contents of GRUB_CMDLINE_LINUX in /etc/default/grub
      command: grep GRUB_CMDLINE_LINUX /etc/default/grub
      register: grep_default_grub_result
      changed_when: no

    - name: Assert that processor.max_cstate=1 is in GRUB_CMDLINE_LINUX in /etc/default/grub
      assert:
        that:
          - "'transparent_hugepage=never' in grep_default_grub_result.stdout"
        fail_msg: "FAIL: 'transparent_hugepage=never' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'transparent_hugepage=never' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

  when: sap_hana_preconfigure_modify_grub_cmdline_linux or
        sap_hana_preconfigure_assert_all_config|d(false)

...
