---
# tasks file for sap-hana-preconfigure/handlers/main.yml:

# regenerate-grub2-conf.yml: Regerate grub2 config
  - debug:
      msg: "Regerate grub2 config"

  - name: "Check if server is booted in BIOS or UEFI mode"
    stat:
      path: /sys/firmware/efi
      get_checksum: no
    register: efi_exists
  - debug:
      var: efi_exists.stat.exists

  - name: "Run grub-mkconfig (BIOS mode)"
    command: bash -lc "grub2-mkconfig -o /boot/grub2/grub.cfg"
    register: command_result
    when:
      - not efi_exists.stat.exists
      - sap_hana_preconfigure_run_grub2_mkconfig
  - debug:
      var: command_result.stdout_lines, command_result.stderr_lines

  - name: "Run grub-mkconfig (UEFI mode)"
    command: bash -lc "grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg"
    register: command_result
    when:
      - efi_exists.stat.exists
      - sap_hana_preconfigure_run_grub2_mkconfig
  - debug:
      var: command_result.stdout_lines, command_result.stderr_lines

